# CUSTOM SCALAR TYPES
scalar Date

# TYPES
type User {
	_id: ID
	name: String!
	email: String!
	password: String!
	createdAt: String!
	log: [Session]
}

type Session {
	_id: ID!
	newSession: Boolean
	createdAt: String
	updatedAt: String
	title: String!
	sessionDate: Date!
	exercises: [Exercise]
	notes: String
	creator: User
}

type Exercise {
	id: Int!
	name: String!
	sets: [Set]
}

type Set {
	id: Int!
	setQty: Int!
	repQty: Int!
	weight: String!
}

type AuthData {
	token: String!
}

# INPUT TYPES
input SessionInput {
	_id: ID!
	newSession: Boolean
	createdAt: String
	updatedAt: String
	title: String!
	sessionDate: Date!
	exercises: [ExerciseInput]
	notes: String
}

input ExerciseInput {
	id: Int!
	name: String!
	sets: [SetInput]
}

input SetInput {
	id: Int!
	setQty: Int
	repQty: Int
	weight: String
}

# ROOT
type Query {
	getUserData: User
	getSessionByID(sessionId: ID!): Session
	getSessionsByTitle(title: String!): [Session]
	getSessionsFromTo(fromDate: Date!, toDate: Date!): [Session]
	isAuth(token: String!): Boolean
}

type Mutation {
	signupUser(name: String!, email: String!, password: String!): AuthData!
	loginUser(email: String!, password: String!): AuthData!
	createSession(sessionDate: Date!): Session!
	saveSession(sessionData: SessionInput!): Session!
	deleteSession(sessionId: ID!): Boolean
}
